-- Import parent-facing story details from the Storie Pakkie Inligting.docx source.
-- These details power the Luister story summary card.

with updates (
    slug,
    source_title,
    synopsis,
    lessons,
    values_display,
    value_tags,
    questions,
    characters
) as (
values
    ($$suurlemoentjie$$, $$Suurlemoentjie$$, $$Suurlemoentjie probeer ander help, maar haar "suur" manier van praat maak dat ander seerkry en nie wil luister nie. Sy leer uiteindelik om haar woorde sagter en vriendeliker te gebruik.$$, array[$$Hoe jy iets sê is net so belangrik soos wat jy sê$$, $$Woorde kan ander seermaak of help$$]::text[], array[$$Respek$$, $$vriendelikheid$$, $$empatie$$, $$kommunikasie$$]::text[], array[$$respek$$, $$vriendelikheid$$, $$empatie$$, $$kommunikasie$$]::text[], array[$$Hoe het Suurlemoentjie ander laat voel toe sy gepraat het?$$, $$Hoe kan ons iets sê sonder om iemand seer te maak?$$, $$Het iemand al iets vir jou gesê wat jou hartseer gemaak het?$$]::text[], array[$$Suurlemoentjie$$, $$Piesang$$, $$Lemoen$$, $$Oom Pynie (Pynappel)$$, $$ander vrugte$$]::text[]),
    ($$benjamin-die-bulhond$$, $$Ben die Bulhond$$, $$Ben speel in die modder en maak Wendy se huis en bed vuil. Hy besef later sy fout en probeer dit regmaak.$$, array[$$Dink aan ander se gevoelens en besittings$$, $$Neem verantwoordelikheid vir jou dade$$]::text[], array[$$Verantwoordelikheid$$, $$respek$$, $$omgee$$, $$eerlikheid$$]::text[], array[$$verantwoordelikheid$$, $$respek$$, $$omgee$$, $$eerlikheid$$]::text[], array[$$Het Ben die regte besluit geneem toe hy op Wendy se bed klim?$$, $$Hoe het Wendy gevoel toe sy haar kamer sien?$$, $$Wat het Ben gedoen om sy fout reg te maak?$$]::text[], array[$$Ben$$, $$Wendy$$, $$Wendy se Mamma$$]::text[]),
    ($$tiekie-tik-tik-tok$$, $$Tiekie tik tik tok$$, $$Tiekie sukkel met sy aanhoudende "tik tik tok", maar leer dat dit sy doel en belangrike werk is.$$, array[$$Aanvaar wie jy is en jou doel$$, $$Alles het 'n rede en waarde$$]::text[], array[$$Selfaanvaarding$$, $$doel$$, $$dankbaarheid$$]::text[], array[$$selfaanvaarding$$, $$doel$$, $$dankbaarheid$$]::text[], array[$$Hoekom het Tiekie nie van sy tik tik tok gehou nie?$$, $$Wat het Oupa Horlosie hom geleer?$$, $$Wat maak jou spesiaal?$$]::text[], array[$$Tiekie$$, $$Oupa Horlosie$$]::text[]),
    ($$skilpad-op-die-geduldpad$$, $$Skilpad op die geduld pad$$, $$Haastige Henry leer deur 'n reis op die "geduld-pad" om stadiger te leef, mooi te kyk en nie op te gee nie.$$, array[$$Geduld bring beloning$$, $$Moenie opgee nie$$, $$Wees teenwoordig en let op$$]::text[], array[$$Geduld$$, $$deursettingsvermoë$$, $$bewustheid$$]::text[], array[$$geduld$$, $$deursettingsvermoë$$, $$bewustheid$$]::text[], array[$$Hoekom was Henry altyd haastig?$$, $$Wat het gebeur toe hy nie mooi gekyk het nie?$$, $$Wat het hy aan die einde geleer?$$]::text[], array[$$Henry (Haastige Henry)$$, $$ou Skilpad$$, $$ander skilpaaie$$]::text[]),
    ($$die-kwaaibok-se-klip$$, $$Die Kwaai bok se klip$$, $$'n Kwaai bok luister nie na ander nie en sit op 'n gebreekte klip. Hy leer uiteindelik om na raad te luister en waardeer sy vriende.$$, array[$$Luister na ander se raad$$, $$Moenie koppig wees nie$$]::text[], array[$$Nederigheid$$, $$luister$$, $$vriendskap$$]::text[], array[$$nederigheid$$, $$luister$$, $$vriendskap$$]::text[], array[$$Hoekom wou die bok nie luister nie?$$, $$Wat het gebeur toe hy nie geluister het nie?$$, $$Wie het hom gehelp?$$]::text[], array[$$Kwaaibok$$, $$Hasie$$, $$voëltjies$$, $$Skilpad$$]::text[]),
    ($$georgie-se-radio$$, $$Georgie se Radio$$, $$Georgie geniet sy musiek en dans, maar besef nie dit steur ander nie. Hy leer om ander in ag te neem.$$, array[$$Wees bewus van ander$$, $$Balans tussen jou eie en ander se behoeftes$$]::text[], array[$$Respek$$, $$samewerking$$, $$bewustheid$$]::text[], array[$$respek$$, $$samewerking$$, $$bewustheid$$]::text[], array[$$Hoekom was die ander diere kwaad vir Georgie?$$, $$Wat kon Georgie anders doen?$$, $$Hoe kan ons almal gelukkig wees saam?$$]::text[], array[$$Georgie$$, $$Jannie die Luidier$$, $$Gertman die Gemsbok$$, $$Louis die Leeu$$, $$Dirk die Olifant$$, $$ander diere$$]::text[]),
    ($$prinses-panda$$, $$Prinses Panda se skoenlapper dans$$, $$Prinses Panda wil dans maar sukkel. Met hulp en oefening bereik sy haar droom.$$, array[$$Moenie opgee nie$$, $$Oefening en ondersteuning help jou groei$$]::text[], array[$$Deursettingsvermoë$$, $$selfvertroue$$, $$ondersteuning$$]::text[], array[$$deursettingsvermoë$$, $$selfvertroue$$, $$ondersteuning$$]::text[], array[$$Hoekom het Prinses Panda aanvanklik gesukkel?$$, $$Wie het haar gehelp?$$, $$Wat gebeur as ons aanhou oefen?$$]::text[], array[$$Prinses Panda$$, $$skoenlappertjie$$, $$flaminke$$]::text[]),
    ($$daantjie-en-sy-waentjie$$, $$Daantjie en sy waentjie$$, $$Daantjie hou aan om al hoe meer goed te versamel totdat sy waentjie te swaar raak en hom amper in gevaar bring. Hy leer om te deel en nie alles te wil hê nie.$$, array[$$Te veel hê kan probleme veroorsaak$$, $$Leer om te deel en nee te sê$$]::text[], array[$$Selfbeheersing$$, $$deel$$, $$tevredenheid$$]::text[], array[$$selfbeheersing$$, $$deel$$, $$tevredenheid$$]::text[], array[$$Hoekom wou Daantjie alles hê?$$, $$Wat het gebeur toe sy waentjie te swaar geword het?$$, $$Hoekom is dit goed om te deel?$$]::text[], array[$$Daantjie$$]::text[]),
    ($$grootseun-die-wildebakkie$$, $$Grootseun, die wilde bakkie!$$, $$Grootseun hou daarvan om wild te jaag, maar leer om eers te dink en reëls te volg deur die raad van Snorre die Spietkop.$$, array[$$Dink voordat jy optree$$, $$Volg reëls vir veiligheid en respek$$]::text[], array[$$Selfbeheer$$, $$respek$$, $$verantwoordelikheid$$]::text[], array[$$selfbeheer$$, $$respek$$, $$verantwoordelikheid$$]::text[], array[$$Wat beteken "sit 'n stop in jou kop"?$$, $$Wat het gebeur toe Grootseun nie gestop het nie?$$, $$Wanneer moet ons eers dink voordat ons iets doen?$$]::text[], array[$$Grootseun$$, $$Snorre die Spietkop$$, $$Mamma$$, $$Tannie Vollie van As$$, $$Wiele$$, $$Tannie Bets Bussie$$]::text[]),
    ($$rammetjie-uitnek$$, $$Rammetjie Uitnek!$$, $$Rammetjie stamp ander maaitjies en maak hulle seer totdat hy self teen iemand groter vasloop en leer om sagter te speel.$$, array[$$Moenie ander seermaak nie$$, $$Leer uit jou foute$$]::text[], array[$$Respek$$, $$empatie$$, $$selfbeheer$$]::text[], array[$$respek$$, $$empatie$$, $$selfbeheer$$]::text[], array[$$Hoekom het die ander maaitjies nie van Rammetjie gehou nie?$$, $$Wat het gebeur toe hy vir Rudi Renoster ontmoet het?$$, $$Hoe kan ons mooi speel saam met ander?$$]::text[], array[$$Rammetjie Uitnek$$, $$Niklaas die Hasie$$, $$Stefaans die Hoenderhaan$$, $$Rudi Renoster$$, $$ander maaitjies$$]::text[]),
    ($$dit-was-jou-stert$$, $$Dit was jou stert!$$, $$Floris is baie nuuskierig, maar verstaan nie hoekom dinge breek nie - tot hy besef dit is sy eie stert wat die skade veroorsaak.$$, array[$$Wees bewus van jou eie optrede$$, $$Neem verantwoordelikheid vir wat jy doen$$]::text[], array[$$Selfbewustheid$$, $$verantwoordelikheid$$, $$leer$$]::text[], array[$$selfbewustheid$$, $$verantwoordelikheid$$, $$leer$$]::text[], array[$$Hoekom het dinge gebreek rondom Floris?$$, $$Hoe het hy uitgevind wat die probleem is?$$, $$Wat kan ons doen om meer bewus te wees van wat ons doen?$$]::text[], array[$$Floris Dinosaurus$$]::text[]),
    ($$nah-nah$$, $$Nah Nah-Nah boe boe!$$, $$Sussa seemeeu terg die see en speel rof totdat sy deur 'n brander omgeslaan word en leer om versigtig en respekvol te wees.$$, array[$$Moenie roekeloos wees nie$$, $$Luister na waarskuwings$$]::text[], array[$$Respek$$, $$versigtigheid$$, $$gehoorsaamheid$$]::text[], array[$$respek$$, $$versigtigheid$$, $$gehoorsaamheid$$]::text[], array[$$Hoekom het Sussa in die moeilikheid beland?$$, $$Wat het haar boeta vir haar gesê?$$, $$Hoekom is dit belangrik om na waarskuwings te luister?$$]::text[], array[$$Sussa seemeeu$$, $$Boeta seemeeu$$, $$Mamma$$, $$Pappa$$]::text[]),
    ($$die-kwaai-grommel-grom$$, $$Die Kwaai Grommel$$, $$Grommel is heeltyd kwaai en baklei, maar dit blyk hy is net moeg. Nadat hy rus, voel hy beter.$$, array[$$Emosies kan kom van moegheid$$, $$Rus en selfversorging is belangrik$$]::text[], array[$$Selfbewustheid$$, $$emosionele intelligensie$$, $$sorg$$]::text[], array[$$selfbewustheid$$, $$emosionele intelligensie$$, $$sorg$$]::text[], array[$$Hoekom was Grommel so kwaai?$$, $$Wat het gebeur toe hy slaap?$$, $$Hoe voel jy wanneer jy baie moeg is?$$]::text[], array[$$Grommel$$, $$Boeta$$, $$Sussa$$]::text[]),
    ($$diekwaaigrommel$$, $$Die Kwaai Grommel$$, $$Grommel is heeltyd kwaai en baklei, maar dit blyk hy is net moeg. Nadat hy rus, voel hy beter.$$, array[$$Emosies kan kom van moegheid$$, $$Rus en selfversorging is belangrik$$]::text[], array[$$Selfbewustheid$$, $$emosionele intelligensie$$, $$sorg$$]::text[], array[$$selfbewustheid$$, $$emosionele intelligensie$$, $$sorg$$]::text[], array[$$Hoekom was Grommel so kwaai?$$, $$Wat het gebeur toe hy slaap?$$, $$Hoe voel jy wanneer jy baie moeg is?$$]::text[], array[$$Grommel$$, $$Boeta$$, $$Sussa$$]::text[]),
    ($$stewels$$, $$Stewels$$, $$Stewels voel uitgesluit omdat sy anders is, maar leer dat haar vrees haar terughou en vind uiteindelik vriende wanneer sy dit oorkom.$$, array[$$Moenie bang wees om nuwe dinge te probeer nie$$, $$Wees jouself en gee ander 'n kans$$]::text[], array[$$Selfvertroue$$, $$aanvaarding$$, $$moed$$]::text[], array[$$selfvertroue$$, $$aanvaarding$$, $$moed$$]::text[], array[$$Hoekom het die ander flaminke vir Stewels vermy?$$, $$Waarvoor was Stewels bang?$$, $$Wat het verander toe sy haar stewels uittrek?$$]::text[], array[$$Stewels$$, $$ander flaminkies$$, $$mamma en pappa flaminke$$]::text[]),
    ($$die-buffel-baas$$, $$Die Buffel-baas$$, $$Mnr. De Buffel raak oorweldig deur werk en besluite totdat hy besef hy moet fokus op wat hy goed doen en hulp kry waar nodig.$$, array[$$Ken jou sterkpunte$$, $$Vra vir hulp en deel verantwoordelikheid$$]::text[], array[$$Samewerking$$, $$selfinsig$$, $$balans$$]::text[], array[$$samewerking$$, $$selfinsig$$, $$balans$$]::text[], array[$$Hoekom was Mnr. De Buffel ongelukkig?$$, $$Wat het hom gehelp om beter te voel?$$, $$Waarmee is jy goed en waarmee het jy hulp nodig?$$]::text[], array[$$Mnr. De Buffel$$, $$Ruben die rooibekrenostervoëltjie$$, $$verskeie diere (olifant, oerangoetang, sjimpansee, ens.)$$]::text[]),
    ($$oom-boom$$, $$Oom Boom$$, $$Oom Boom is 'n ou boom wat langs 'n voetpaadjie staan en deur die jaar kyk hoe kinders verbygaan. Hy beleef al vier seisoene - van die vrolike lente tot die stil, koue winter - en leer dat alles verander, maar dat goeie tye altyd weer terugkom.$$, array[$$Seisoene en moeilike tye gaan verby$$, $$Hoop bly altyd oor$$]::text[], array[$$Hoop$$, $$Geduld$$, $$Aanvaarding$$]::text[], array[$$hoop$$, $$geduld$$, $$aanvaarding$$]::text[], array[$$Watter seisoen hou jy die meeste van en hoekom?$$, $$Hoe het Oom Boom gevoel in die winter?$$, $$Wat gebeur altyd weer na die winter?$$]::text[], array[$$Oom Boom$$, $$kinders$$, $$Mamma's$$, $$Pappa's$$]::text[]),
    ($$die-fluistervarke$$, $$Die Fluistervarke$$, $$Drie wilde varkies hou daarvan om rof en hard te speel, maar hulle maak heeltyd hulle baba boetie wakker. Hulle leer om sagter te speel en verander selfs hul naam na die Fluistervarke - ten minste vir 'n rukkie!$$, array[$$Dink aan ander wanneer jy speel$$, $$Selfbeheer is belangrik$$]::text[], array[$$Respek$$, $$Selfbeheer$$, $$Omgee$$]::text[], array[$$respek$$, $$selfbeheer$$, $$omgee$$]::text[], array[$$Hoekom moes die varkies stiller speel?$$, $$Hoe kan jy speel sonder om ander te pla?$$, $$Wanneer is dit reg om hard te speel?$$]::text[], array[$$Ompel$$, $$Strompel$$, $$Snoet$$, $$baba boetie$$, $$Mamma Vark$$]::text[]),
    ($$haily-hasie-se-groentetuin$$, $$Hailey Hasie se groentetuin$$, $$Hailey Hasie werk hard in haar groentetuin, maar raak hartseer toe 'n maatjie lelik is met haar. Haar mamma verduidelik dat vriendskap soos 'n tuin is - dit vat liefde, moeite en sorg om te groei.$$, array[$$Ware vriendskap vat moeite$$, $$Wees eerste 'n goeie maatjie$$]::text[], array[$$Vriendskap$$, $$Empatie$$, $$Respek$$]::text[], array[$$vriendskap$$, $$empatie$$, $$respek$$]::text[], array[$$Wat maak 'n goeie maatjie?$$, $$Hoe kan jy iemand beter laat voel?$$, $$Wat beteken dit om 'n "saadjie" van vriendskap te plant?$$]::text[], array[$$Hailey Hasie$$, $$Mamma Hasie$$, $$maatjie$$]::text[]),
    ($$arno-arend-sprei-sy-vlerke$$, $$Arno Arend sprei sy vlerke$$, $$Arno, 'n jong visarend, wil leer vlieg soos sy pappa. Hy probeer oor en oor, al val hy baie keer, totdat hy uiteindelik daarin slaag om sy vlerke te sprei en te vlieg.$$, array[$$Moenie opgee nie$$, $$Oefening maak jou sterker$$]::text[], array[$$Deursettingsvermoë$$, $$Moed$$, $$Selfvertroue$$]::text[], array[$$deursettingsvermoë$$, $$moed$$, $$selfvertroue$$]::text[], array[$$Het jy al iets probeer wat moeilik was?$$, $$Hoe het Arno gevoel toe hy geval het?$$, $$Wat het hom gehelp om weer te probeer?$$]::text[], array[$$Arno Arend$$, $$Barend die Arend (Pappa)$$, $$Mamma Arend$$]::text[]),
    ($$maniere-wys-jou-spiere$$, $$Maniere wys jou spiere$$, $$Meneer Maniere leer dat goeie maniere soos spiere is - hoe meer jy dit gebruik, hoe sterker word dit. Hy oefen om vriendelik te wees, te deel en respek te wys, selfs wanneer dit moeilik is.$$, array[$$Goeie maniere maak 'n groot verskil$$, $$Kies om die regte ding te doen$$]::text[], array[$$Respek$$, $$Vriendelikheid$$, $$Verantwoordelikheid$$]::text[], array[$$respek$$, $$vriendelikheid$$, $$verantwoordelikheid$$]::text[], array[$$Wat is goeie maniere?$$, $$Wanneer is dit moeilik om goeie maniere te gebruik?$$, $$Hoe laat goeie maniere ander mense voel?$$]::text[], array[$$Meneer Maniere$$, $$kinders by die snoepwinkel$$]::text[]),
    ($$llama-llama-pajama-llama$$, $$Lama Lama Pajama Lama$$, $$Lama Lama dink hy weet alles en luister nie na sy mamma nie. Een dag gaan hy skool toe in sy pajamas en leer 'n belangrike les oor luister en respek.$$, array[$$Luister na jou ouers$$, $$Jy hoef nie altyd terug te praat nie$$]::text[], array[$$Respek$$, $$Luister$$, $$Nederigheid$$]::text[], array[$$respek$$, $$luister$$, $$nederigheid$$]::text[], array[$$Hoekom het Llama Llama in sy pajamas skool toe gegaan?$$, $$Wat sou jy anders gedoen het?$$, $$Hoekom is dit belangrik om te luister?$$]::text[], array[$$Lama Lama$$, $$Mama Lama$$, $$maats$$, $$Juffrou$$]::text[]),
    ($$sjimpie-se-simfonie$$, $$Sjimpie se Simfonie$$, $$Sjimpie droom daarvan om 'n groot dirigent te wees, al spot die ander ape met hom. Na 'n groot val beland hy op 'n verhoog waar hy sy droom uitleef en almal verstom.$$, array[$$Glo in jou drome$$, $$Moenie luister na negatiewe stemme nie$$]::text[], array[$$Selfvertroue$$, $$Droom$$, $$Volharding$$]::text[], array[$$selfvertroue$$, $$droom$$, $$volharding$$]::text[], array[$$Wat is jou droom?$$, $$Hoe het Sjimpie gevoel toe ander vir hom gelag het?$$, $$Wat het gebeur toe hy nie opgegee het nie?$$]::text[], array[$$Sjimpie$$, $$ander ape$$, $$orkes$$]::text[]),
    ($$seekoei-sluit-sy-mond-toe$$, $$Seekoei sluit sy mond toe$$, $$Swys wil nie sy kos eet nie en dink dit lyk snaaks. Later voel hy siek en leer dat kos belangrik is om jou liggaam sterk en gesond te hou.$$, array[$$Eet jou kos om gesond te bly$$, $$Probeer eers voordat jy besluit$$]::text[], array[$$Gesondheid$$, $$Gehoorsaamheid$$, $$Verantwoordelikheid$$]::text[], array[$$gesondheid$$, $$gehoorsaamheid$$, $$verantwoordelikheid$$]::text[], array[$$Hoekom wou Swys nie eet nie?$$, $$Hoe het hy gevoel toe hy nie geëet het nie?$$, $$Hoekom is kos belangrik?$$]::text[], array[$$Swys Seekoei$$, $$Mamma Seekoei$$, $$Pappa Seekoei$$]::text[]),
    ($$grotman-grootman$$, $$Grotman Grootman$$, $$Grotman is baie skaam en bly alleen in sy grot. Hy leer om dapper te wees en uiteindelik maak hy 'n maatjie - Dot die dinosourus.$$, array[$$Dit vat moed om uit jou dop te kom$$, $$Vriendskap begin met 'n eerste tree$$]::text[], array[$$Moed$$, $$Vriendskap$$, $$Selfvertroue$$]::text[], array[$$moed$$, $$vriendskap$$, $$selfvertroue$$]::text[], array[$$Hoekom was Grotman skaam?$$, $$Wat het hom gehelp om dapper te wees?$$, $$Hoe maak 'n mens nuwe maatjies?$$]::text[], array[$$Grotman$$, $$Dot die dinosourus$$]::text[])
)
update public.stories as story
set
    summary = updates.synopsis,
    description = updates.synopsis,
    tags = (
        select coalesce(array_agg(tag order by tag), array[]::text[])
        from (
            select distinct lower(btrim(tag)) as tag
            from unnest(coalesce(story.tags, array[]::text[]) || coalesce(updates.value_tags, array[]::text[])) as tag
            where tag is not null
              and btrim(tag) <> ''
        ) as merged_tags
    ),
    metadata = jsonb_set(
        coalesce(story.metadata, '{}'::jsonb),
        '{story_details}',
        jsonb_build_object(
            'source', 'Storie Pakkie Inligting.docx',
            'source_title', updates.source_title,
            'synopsis', updates.synopsis,
            'lessons', to_jsonb(updates.lessons),
            'values', to_jsonb(updates.values_display),
            'value_tags', to_jsonb(updates.value_tags),
            'conversation_questions', to_jsonb(updates.questions),
            'characters', to_jsonb(updates.characters),
            'imported_at_utc', to_char(timezone('utc', now()), 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
        ),
        true
    )
from updates
where story.slug = updates.slug;
