create extension if not exists pgcrypto;

create table if not exists public.story_characters (
    character_id uuid primary key default gen_random_uuid(),
    slug text not null unique,
    display_name text not null,
    tagline text,
    species text,
    habitat text,
    catchphrase text,
    favorite_thing text,
    character_trait text,
    golden_lesson text,
    core_value text,
    first_appearance text,
    friends text,
    reflection_question text,
    challenge_text text,
    image_path text,
    mystery_image_path text,
    image_drive_file_id text,
    mystery_image_drive_file_id text,
    unlock_story_slug text references public.stories(slug) on update cascade on delete set null,
    related_story_slugs text[] not null default '{}'::text[],
    unlock_threshold_seconds integer not null default 30,
    status text not null default 'draft',
    sort_order integer not null default 0,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint story_characters_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
    constraint story_characters_slug_not_blank check (btrim(slug) <> ''),
    constraint story_characters_display_name_not_blank check (btrim(display_name) <> ''),
    constraint story_characters_status_check check (status in ('draft', 'published', 'archived')),
    constraint story_characters_unlock_threshold_check check (unlock_threshold_seconds between 1 and 3600),
    constraint story_characters_image_path_not_blank check (image_path is null or btrim(image_path) <> ''),
    constraint story_characters_mystery_path_not_blank check (mystery_image_path is null or btrim(mystery_image_path) <> ''),
    constraint story_characters_image_drive_id_not_blank check (image_drive_file_id is null or btrim(image_drive_file_id) <> ''),
    constraint story_characters_mystery_drive_id_not_blank check (mystery_image_drive_file_id is null or btrim(mystery_image_drive_file_id) <> '')
);

comment on table public.story_characters is 'Character profiles and unlock metadata shown on /karakters.';
comment on column public.story_characters.unlock_story_slug is 'Primary story slug that unlocks the character after enough listening progress.';
comment on column public.story_characters.related_story_slugs is 'Story slugs associated with the character for display and unlock fallback.';
comment on column public.story_characters.metadata is 'Flexible JSON metadata for import/source notes.';

create index if not exists idx_story_characters_status_sort
    on public.story_characters(status, sort_order, display_name);

create index if not exists idx_story_characters_unlock_story
    on public.story_characters(unlock_story_slug);

create index if not exists idx_story_characters_related_stories
    on public.story_characters using gin (related_story_slugs);

create index if not exists idx_story_characters_metadata
    on public.story_characters using gin (metadata jsonb_path_ops);

alter table public.story_characters enable row level security;

drop policy if exists story_characters_read_published on public.story_characters;
create policy story_characters_read_published
on public.story_characters
for select
to anon, authenticated
using (status = 'published');

drop policy if exists story_characters_service_role_all on public.story_characters;
create policy story_characters_service_role_all
on public.story_characters
for all
to service_role
using (true)
with check (true);

drop trigger if exists trg_story_characters_set_updated_at on public.story_characters;
create trigger trg_story_characters_set_updated_at
before update on public.story_characters
for each row execute function public.set_updated_at();

with seed_rows as (
    select *
    from (
        values
            (
                0,
                'roomie',
                'Roomie',
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                'Suurlemoentjie (2024).',
                null,
                null,
                null,
                '1KpvkjM0W8KdPOlWZEqFaJg9N3wFuGerF',
                '1TwlFEQ0ozmxF-TJMgg2iYzNo7kvu1KZM',
                'suurlemoentjie',
                array['suurlemoentjie']::text[],
                30,
                'published',
                jsonb_build_object('seed_source', 'google_drive_folder', 'seed_date', '2026-04-09', 'notes', 'Unlock story assumed from starter story until confirmed.')
            ),
            (
                10,
                'suurlemoentjie',
                'Suurlemoentjie',
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                'Suurlemoentjie (2024).',
                null,
                null,
                null,
                '1OT7XrhbTFWAUpjb42qXZhcxo9Dh5D1dl',
                '1_S8DbwE69YJB8MPwIIE6r00Lx8TvzbWd',
                'suurlemoentjie',
                array['suurlemoentjie']::text[],
                30,
                'published',
                jsonb_build_object('seed_source', 'google_drive_folder', 'seed_date', '2026-04-09')
            ),
            (
                20,
                'benjamin-die-bulhond',
                'Benjamin die Bulhond',
                null,
                'Bulhond',
                null,
                null,
                null,
                null,
                null,
                null,
                'Benjamin Die Bulhond (2024).',
                null,
                null,
                null,
                '1aErt_GTg7Bu0PNiiI0vHiSD7tB2EVIEo',
                '15QUoW3CucFavRWBVFfin9wFUzoV1qyUy',
                'benjamin-die-bulhond',
                array['benjamin-die-bulhond']::text[],
                30,
                'published',
                jsonb_build_object('seed_source', 'google_drive_folder', 'seed_date', '2026-04-09')
            ),
            (
                30,
                'tiekie',
                'Tiekie',
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                'Tiekie Tik Tik Tok (2024).',
                null,
                null,
                null,
                '1DjTjiyZpprldGq13qbqJBz3lFAwbbACn',
                '1d0VQcFeWIXPx7hWlOpMy04I1lc5aE7hq',
                'tiekie-tik-tik-tok',
                array['tiekie-tik-tik-tok']::text[],
                30,
                'published',
                jsonb_build_object('seed_source', 'google_drive_folder', 'seed_date', '2026-04-09')
            ),
            (
                40,
                'henry-skilpad',
                'Henry Skilpad',
                null,
                'Skilpad',
                null,
                null,
                null,
                null,
                null,
                null,
                'Skilpad op die Geduldpad (2024).',
                null,
                null,
                null,
                '1kozcXRzLWYQXZUg4H4DFgJYcsMBTVOgr',
                '1BGWj0w-B-myPrssgF-BsjoWzP5s7hjI7',
                'skilpad-op-die-geduldpad',
                array['skilpad-op-die-geduldpad']::text[],
                30,
                'published',
                jsonb_build_object('seed_source', 'google_drive_folder', 'seed_date', '2026-04-09')
            ),
            (
                50,
                'die-kwaaibok',
                'Die Kwaaibok',
                '''n Koppige bokkie wat leer dat ''n ''asseblief'' deure (en harte) oopmaak.',
                'Bok (Steenbok)',
                'Die Hangklip (bo die wolke)',
                'Hierdie is MY klip, kant en klaar!',
                'Om hoog bo die wereld op sy eie klip te sit.',
                'Hy is vinnig kwaad en baie ongeduldig met ander.',
                'Mooi vra, mooi kry.',
                'Geduld / Dankbaarheid',
                'Die Kwaaibok se Klip (2025).',
                'Skilpad, Hasie, die Voeltjies en Arend.',
                'Was jy al ooit so kwaad dat jy nie wou luister na goeie raad nie?',
                'As jy vandag ongeduldig voel, haal diep asem en vra mooi vir hulp, net soos Kwaaibok geleer het om te doen.',
                '1TDENu7NUk8euzo0ZvaoPXxnN7Lk2sR6r',
                '19DN0KuxWdIvcBJdt5vw1TYRoaXhDfKFf',
                'die-kwaaibok-se-klip',
                array['die-kwaaibok-se-klip', 'die-kwaai-bok-sit-vas']::text[],
                30,
                'published',
                jsonb_build_object('seed_source', 'google_drive_folder', 'template_source', 'Karakter Profiel.docx', 'seed_date', '2026-04-09')
            ),
            (
                60,
                'georgie',
                'Georgie',
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                'Georgie se Radio (2024).',
                null,
                null,
                null,
                '1mkZNaiVo2dK_B_FR7jk-u0C9DRj0KpPc',
                '1VmlpnT6wZzEPByaAChSkLaXY_1-IeZRX',
                'georgie-se-radio',
                array['georgie-se-radio']::text[],
                30,
                'published',
                jsonb_build_object('seed_source', 'google_drive_folder', 'seed_date', '2026-04-09')
            ),
            (
                70,
                'prinses-panda',
                'Prinses Panda',
                null,
                'Panda',
                null,
                null,
                null,
                null,
                null,
                null,
                'Prinses Panda (2024).',
                null,
                null,
                null,
                '199MvTicLWCgjy__qeQeGRA6aBRV7cIaR',
                '19aOZvRcPiBCIL0gHCXyMdvKcGt6zxbnm',
                'prinses-panda',
                array['prinses-panda']::text[],
                30,
                'published',
                jsonb_build_object('seed_source', 'google_drive_folder', 'seed_date', '2026-04-09')
            ),
            (
                80,
                'daantjie',
                'Daantjie',
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                'Daantjie en sy waentjie (2024).',
                null,
                null,
                null,
                '1mLAwdeyC2jQbQAXtNYRGH-djEBUTLe2-',
                '15INYYIt5n8GSRBqig6nF1iIW1S_9GXPP',
                'daantjie-en-sy-waentjie',
                array['daantjie-en-sy-waentjie']::text[],
                30,
                'published',
                jsonb_build_object('seed_source', 'google_drive_folder', 'seed_date', '2026-04-09')
            ),
            (
                90,
                'grootseun-die-wilde-bakkie',
                'Grootseun die Wilde bakkie',
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                'Grootseun Die WildeBakkie (2024).',
                null,
                null,
                null,
                '1txN-uwLgQHtV_Siw5OYKTYKb5iQiEDcf',
                '1tppt_VSkjPIonPCkD5fSKCgiG_U7V5gU',
                'grootseun-die-wildebakkie',
                array['grootseun-die-wildebakkie']::text[],
                30,
                'published',
                jsonb_build_object('seed_source', 'google_drive_folder', 'seed_date', '2026-04-09')
            ),
            (
                100,
                'rammetjie-uitnek',
                'Rammetjie Uitnek',
                null,
                'Ram',
                null,
                null,
                null,
                null,
                null,
                null,
                'Rammetjie Uitnek (2024).',
                null,
                null,
                null,
                '1Kf6OkVWN7Ap5aqOrqHrnWTIAV6ngfEq3',
                '1BL7tvyj-ge78ZNEfiX_3pmJDTo53sN1E',
                'rammetjie-uitnek',
                array['rammetjie-uitnek']::text[],
                30,
                'published',
                jsonb_build_object('seed_source', 'google_drive_folder', 'seed_date', '2026-04-09')
            ),
            (
                110,
                'floris-dinosaurus',
                'Floris Dinosaurus',
                null,
                'Dinosaurus',
                null,
                null,
                null,
                null,
                null,
                null,
                'Dinosaurus is Moeg (2025).',
                null,
                null,
                null,
                '1a20mPtpTAmJis0j7VXQWS1sjTcCaRNfs',
                '1tw33usiJeti7QGu9sxc6dCPiYGIV0jiI',
                'dinosaurus-is-moeg',
                array['dinosaurus-is-moeg']::text[],
                30,
                'published',
                jsonb_build_object('seed_source', 'google_drive_folder', 'seed_date', '2026-04-09', 'notes', 'Unlock story assumed from title match.')
            ),
            (
                120,
                'sussa-seeumeeu',
                'Sussa Seeumeeu',
                null,
                'Seeumeeu',
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                '1X2L_wpVmuwjWNmErbT0NqTkOrK9OsxJM',
                '1leP7U8Bnkm2FiVCft15w_Mk1NdRFD_D0',
                'sarel-swaeltje-pak-sy-tassie',
                array['sarel-swaeltje-pak-sy-tassie']::text[],
                30,
                'published',
                jsonb_build_object('seed_source', 'google_drive_folder', 'seed_date', '2026-04-09', 'notes', 'Unlock story assumed from closest published bird story.')
            ),
            (
                130,
                'boeta-seeumeeu',
                'Boeta Seeumeeu',
                null,
                'Seeumeeu',
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                '1pdLmh_XM6gIP4CptkRJpnluJT6Jkvr1g',
                '1ueq4TsrSxJZhRSvNFhrQmF1biLBNGO6d',
                'sarel-swaeltje-pak-sy-tassie',
                array['sarel-swaeltje-pak-sy-tassie']::text[],
                30,
                'published',
                jsonb_build_object('seed_source', 'google_drive_folder', 'seed_date', '2026-04-09', 'notes', 'Unlock story assumed from closest published bird story.')
            ),
            (
                140,
                'grommel',
                'Grommel',
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                'Die Kwaai Grommel (2024).',
                null,
                null,
                null,
                '1CVWUza3khYm61Akl5V1J-Mj3skEbKC1e',
                '1vjqfe5WI2VGVFE-OlLrCxlxFvEfsvue0',
                'diekwaaigrommel',
                array['diekwaaigrommel', 'die-kwaai-grommel-grom', 'schink-stories-die-kwaai-grommel-grom']::text[],
                30,
                'published',
                jsonb_build_object('seed_source', 'google_drive_folder', 'seed_date', '2026-04-09')
            ),
            (
                150,
                'stewels',
                'Stewels',
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                'Stewels (2024).',
                null,
                null,
                null,
                '1daMWbJ7kSdE_wi8g036idVmtdYQKhNuj',
                '1_kdr2dJ77il4Lf7FUidoRqCCc-gBz7Je',
                'stewels',
                array['stewels']::text[],
                30,
                'published',
                jsonb_build_object('seed_source', 'google_drive_folder', 'seed_date', '2026-04-09')
            ),
            (
                160,
                'meneer-de-buffel',
                'Meneer De Buffel',
                null,
                'Buffel',
                null,
                null,
                null,
                null,
                null,
                null,
                'Die Buffel-baas (2024).',
                null,
                null,
                null,
                '1zON8wxVYYxt41jbPT56YyCFsl7SqQoYO',
                '1L3VzN-Hw4-oKWy-j_KY4elmeKzkE4bFJ',
                'die-buffel-baas',
                array['die-buffel-baas', 'buffel']::text[],
                30,
                'published',
                jsonb_build_object('seed_source', 'google_drive_folder', 'seed_date', '2026-04-09')
            ),
            (
                170,
                'oom-boom',
                'Oom Boom',
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                'Oom Boom (2024).',
                null,
                null,
                null,
                '1o3-Uid7f0w2oFW2YglHKm_J4F23YkARU',
                '17LsWXS3YOS6e5QcYQRJSqGxv9p_n5e7_',
                'oom-boom',
                array['oom-boom']::text[],
                30,
                'published',
                jsonb_build_object('seed_source', 'google_drive_folder', 'seed_date', '2026-04-09')
            ),
            (
                180,
                'ompel',
                'Ompel',
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                'Ompeplompie Obbelop (2025).',
                null,
                null,
                null,
                '1vM6IEwp1p52pLv9xaI9xK0Uze44_5l7k',
                '1sh3SDYRENQykuV1aqOw7_29BmXUmStQV',
                'ompeplompie-obbelop',
                array['ompeplompie-obbelop']::text[],
                30,
                'published',
                jsonb_build_object('seed_source', 'google_drive_folder', 'seed_date', '2026-04-09')
            ),
            (
                190,
                'snoet',
                'Snoet',
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                'Ompeplompie Obbelop (2025).',
                null,
                null,
                null,
                '1nmSWpOIZcX7wmemohuphUl9MsZwnwDvC',
                '1pWHbwZXv5j9VX9WH81pC02uPkd_UiASJ',
                'ompeplompie-obbelop',
                array['ompeplompie-obbelop']::text[],
                30,
                'published',
                jsonb_build_object('seed_source', 'google_drive_folder', 'seed_date', '2026-04-09')
            ),
            (
                200,
                'strompel',
                'Strompel',
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                'Ompeplompie Obbelop (2025).',
                null,
                null,
                null,
                '1xOuEts6xvfPizH_acKwIYFiNN_OuFs2y',
                '1hcaGqtj5ruQ4Aw4Of55QcwweHR5Ce-mK',
                'ompeplompie-obbelop',
                array['ompeplompie-obbelop']::text[],
                30,
                'published',
                jsonb_build_object('seed_source', 'google_drive_folder', 'seed_date', '2026-04-09')
            ),
            (
                210,
                'hailey-hasie',
                'Hailey Hasie',
                null,
                'Hasie',
                null,
                null,
                null,
                null,
                null,
                null,
                'Haily Hasie se Groentetuin (2024).',
                null,
                null,
                null,
                '1sgJQRn2563NepzeKj9png5DPDS7pt-Yd',
                '1zWH1km3YXB4xZTueharHthWzd2sT5DWQ',
                'haily-hasie-se-groentetuin',
                array['haily-hasie-se-groentetuin']::text[],
                30,
                'published',
                jsonb_build_object('seed_source', 'google_drive_folder', 'seed_date', '2026-04-09', 'notes', 'Display name follows artwork spelling; linked story keeps existing catalog slug spelling.')
            ),
            (
                220,
                'arno-arend',
                'Arno Arend',
                null,
                'Arend',
                null,
                null,
                null,
                null,
                null,
                null,
                'Arno Arend Sprei Sy Vlerke (2024).',
                null,
                null,
                null,
                '1nYN2buQHYjAYM4qnrIFwzBgxpjXWcC5W',
                '1lVCCnd8MAexCjfn2PdNG_4Ci3uGHiQG7',
                'arno-arend-sprei-sy-vlerke',
                array['arno-arend-sprei-sy-vlerke']::text[],
                30,
                'published',
                jsonb_build_object('seed_source', 'google_drive_folder', 'seed_date', '2026-04-09')
            ),
            (
                230,
                'meneer-maniere',
                'Meneer Maniere',
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                'Maniere Wys Jou Spiere (2024).',
                null,
                null,
                null,
                '15NPp-Os64Coc0fEZB35-8gWB0oIKbz3K',
                '1UB4E7SiW-5vYiT2hORLOxEuoprBOP1jK',
                'maniere-wys-jou-spiere',
                array['maniere-wys-jou-spiere']::text[],
                30,
                'published',
                jsonb_build_object('seed_source', 'google_drive_folder', 'seed_date', '2026-04-09')
            )
    ) as seed (
        sort_order,
        slug,
        display_name,
        tagline,
        species,
        habitat,
        catchphrase,
        favorite_thing,
        character_trait,
        golden_lesson,
        core_value,
        first_appearance,
        friends,
        reflection_question,
        challenge_text,
        image_drive_file_id,
        mystery_image_drive_file_id,
        unlock_story_slug,
        related_story_slugs,
        unlock_threshold_seconds,
        status,
        metadata
    )
)
insert into public.story_characters (
    slug,
    display_name,
    tagline,
    species,
    habitat,
    catchphrase,
    favorite_thing,
    character_trait,
    golden_lesson,
    core_value,
    first_appearance,
    friends,
    reflection_question,
    challenge_text,
    image_path,
    mystery_image_path,
    image_drive_file_id,
    mystery_image_drive_file_id,
    unlock_story_slug,
    related_story_slugs,
    unlock_threshold_seconds,
    status,
    sort_order,
    metadata
)
select
    seed.slug,
    seed.display_name,
    seed.tagline,
    seed.species,
    seed.habitat,
    seed.catchphrase,
    seed.favorite_thing,
    seed.character_trait,
    seed.golden_lesson,
    seed.core_value,
    seed.first_appearance,
    seed.friends,
    seed.reflection_question,
    seed.challenge_text,
    format('/branding/characters/%s.png', seed.slug),
    format('/branding/characters/%s-mystery.png', seed.slug),
    seed.image_drive_file_id,
    seed.mystery_image_drive_file_id,
    seed.unlock_story_slug,
    seed.related_story_slugs,
    seed.unlock_threshold_seconds,
    seed.status,
    seed.sort_order,
    seed.metadata
from seed_rows as seed
on conflict (slug) do update
set
    display_name = excluded.display_name,
    tagline = excluded.tagline,
    species = excluded.species,
    habitat = excluded.habitat,
    catchphrase = excluded.catchphrase,
    favorite_thing = excluded.favorite_thing,
    character_trait = excluded.character_trait,
    golden_lesson = excluded.golden_lesson,
    core_value = excluded.core_value,
    first_appearance = excluded.first_appearance,
    friends = excluded.friends,
    reflection_question = excluded.reflection_question,
    challenge_text = excluded.challenge_text,
    image_path = excluded.image_path,
    mystery_image_path = excluded.mystery_image_path,
    image_drive_file_id = excluded.image_drive_file_id,
    mystery_image_drive_file_id = excluded.mystery_image_drive_file_id,
    unlock_story_slug = excluded.unlock_story_slug,
    related_story_slugs = excluded.related_story_slugs,
    unlock_threshold_seconds = excluded.unlock_threshold_seconds,
    status = excluded.status,
    sort_order = excluded.sort_order,
    metadata = excluded.metadata;
